### ISSUE TITLE
[Question] referrer warning & generic questions

### ISSUE THREAD

**Issue by leaf-ts** [MeemeeLab/node-anime-viewer#40]
Hello,
I found your app from a post in ani-cli.
So far it seems that it works fine from a few tests that I did but I have a few questions

1. upon the first run, since I do not have vlc, I changed the player to mpv. I was constantly getting redirected to the browser. So I went and deleted the referrer url. After that the mpv plays the video but I get the below warning:
```
Can't playback? Did you set the arguments for video player to add 'Referrer' header?
Playing:
[file] Cannot open file '': No such file or directory
Failed to open .
```
Even though it says Failed to open it continues and plays the video fine.

2. I thought I messed up with the config and since I did not kept the url you had in the player parameters I tried to uninstall the app and reinstall it with no avail. Actually the uninstall command says "could not determine executable to run". So I wanted to ask if were the config gets stored or how can I completely remove it so I can install it from scratch with the default settings.

3. is it possible to set the path where the downloaded file/s will be stored?

Very nice application

Thanks

**Comment by MeemeeLab** [comment]
> I was constantly getting redirected to the browser.

This happens when you have invalid setting (In general the program you specified does not exists)

> After that the mpv plays the video but I get the below warning:

You might have space after player commandline.

> I thought I messed up with the config and since I did not kept the url you had in the player parameters I tried to uninstall the app and reinstall it with no avail. Actually the uninstall command says "could not determine executable to run". So I wanted to ask if were the config gets stored or how can I completely remove it so I can install it from scratch with the default settings.

`--url-referrer` is vlc argument, And it probably cannot be used on mpv, but you can google referrer argument for mpv.
You can delete configuration by deleting config.json file. It's located at application data folder.
https://github.com/MeemeeLab/node-anime-viewer/issues/34#issuecomment-1004822492 (replace history.json with config.json)

>is it possible to set the path where the downloaded file/s will be stored?

No, you can't but it probably will be implemented in new version.

**Comment by MeemeeLab** [comment]
By the way, after release of #37 (Proxy feature), the referrer argument will be no longer needed.

**Comment by leaf-ts** [comment]
thank you very much for your replies !!!
